# INFO: We will source all our functions here.

# TODO: To manage functions use 'functions/' directory
# - to add new functions, create a .zsh file in 'functions/' directory
# - likewise remove the file to remove the function.

# WARNING: Do not edit this file.

FUNCTIONS_DIR=$ZSHRC_DIR/functions

for function in $FUNCTIONS_DIR/*.zsh(.N); do
  source "$function"
done
